In [2]:
import pandas as pd
df= pd.read_csv("cleaned_house.csv")
df=df[['selftext','score']]
df=df.dropna()
#df= df[df['type']=="Adult"]
df

                                               selftext  score
0     realize pretty vague honestly mind long simply...      1
1     know long shot looking song month luck hoping ...      3
2     post dedicated finding unknown unidentifiable ...      4
3                                kind remix like best d      1
4     like minimal micro house playlist you perfect ...      3
...                                                 ...    ...
4861  looking house track long drum break conga djem...      1
4862  trying get year contacted label said would sho...      1
4863  time year yearly round best music year rule si...     17
4864  mine in particular order hard omar s heard che...     11
4865  hey guy first post reddit please bare making m...      2

[4287 rows x 2 columns]

In [3]:
import numpy as np
emo = pd.read_csv('./EMOTION.csv')
emo.columns=['word','emotion','score']
emo=emo[emo['score']>=0.5]
#len(emo)1606
#len(emo[emo['emotion']=='anger'])278
#len(emo[emo['emotion']=='fear'])341
#len(emo[emo['emotion']=='sadness'])249
#len(emo[emo['emotion']=='surprise'])104
#len(emo[emo['emotion']=='anticipation'])53
#len(emo[emo['emotion']=='joy'])283
#len(emo[emo['emotion']=='trust'])118
#len(emo[emo['emotion']=='disgust'])180

emo=emo.reset_index()
emo.columns
del emo['index']
emo['emotion'].unique()

array(['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust'], dtype=object)

In [4]:
len(emo[emo['emotion']=='anger'])

755

In [5]:
df[['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust']]=0

df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,realize pretty vague honestly mind long simply...,1,0,0,0,0,0,0,0,0
1,know long shot looking song month luck hoping ...,3,0,0,0,0,0,0,0,0
2,post dedicated finding unknown unidentifiable ...,4,0,0,0,0,0,0,0,0
3,kind remix like best d,1,0,0,0,0,0,0,0,0
4,like minimal micro house playlist you perfect ...,3,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
4861,looking house track long drum break conga djem...,1,0,0,0,0,0,0,0,0
4862,trying get year contacted label said would sho...,1,0,0,0,0,0,0,0,0
4863,time year yearly round best music year rule si...,17,0,0,0,0,0,0,0,0
4864,mine in particular order hard omar s heard che...,11,0,0,0,0,0,0,0,0
4865,hey guy first post reddit please bare making m...,2,0,0,0,0,0,0,0,0

In [6]:
for i in range(len(emo)):
    index=df[df['selftext'].str.contains(emo.iloc[i]['word'])].index
    for j in range(len(index)):
        ind=index[j]
        score = emo.iloc[i]['score']
        column_index=emo.iloc[i]['emotion']
        original=df.at[ind,column_index]
        df.at[ind,column_index]=original+ score *100

In [7]:
df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,realize pretty vague honestly mind long simply...,1,0,0,0,0,68,0,0,148
1,know long shot looking song month luck hoping ...,3,119,187,119,73,292,108,121,75
2,post dedicated finding unknown unidentifiable ...,4,54,0,0,110,0,60,66,128
3,kind remix like best d,1,0,0,0,0,62,0,0,64
4,like minimal micro house playlist you perfect ...,3,54,0,62,56,264,51,0,109
...,...,...,...,...,...,...,...,...,...,...
4861,looking house track long drum break conga djem...,1,0,75,56,0,82,0,0,150
4862,trying get year contacted label said would sho...,1,54,0,127,56,54,111,0,61
4863,time year yearly round best music year rule si...,17,0,51,0,0,53,0,0,0
4864,mine in particular order hard omar s heard che...,11,235,520,267,333,1148,218,163,385
4865,hey guy first post reddit please bare making m...,2,0,64,65,0,129,0,0,255

In [8]:
# get the column name of max values in every row
df['label']=df[['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust']].idxmax(axis="columns")
df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,label
0,realize pretty vague honestly mind long simply...,1,0,0,0,0,68,0,0,148,trust
1,know long shot looking song month luck hoping ...,3,119,187,119,73,292,108,121,75,joy
2,post dedicated finding unknown unidentifiable ...,4,54,0,0,110,0,60,66,128,trust
3,kind remix like best d,1,0,0,0,0,62,0,0,64,trust
4,like minimal micro house playlist you perfect ...,3,54,0,62,56,264,51,0,109,joy
...,...,...,...,...,...,...,...,...,...,...,...
4861,looking house track long drum break conga djem...,1,0,75,56,0,82,0,0,150,trust
4862,trying get year contacted label said would sho...,1,54,0,127,56,54,111,0,61,disgust
4863,time year yearly round best music year rule si...,17,0,51,0,0,53,0,0,0,joy
4864,mine in particular order hard omar s heard che...,11,235,520,267,333,1148,218,163,385,joy
4865,hey guy first post reddit please bare making m...,2,0,64,65,0,129,0,0,255,trust

In [10]:
#remove stopwords
import nltk
from nltk.corpus import stopwords
#nltk.download("stopwords") #uncomment it when run it for the first time
stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    text = " ".join([word for word in text.split() if word not in stop_words])
    return text

stop_words.update({'would','k','im','could','also',
                   'amp','much','one','like',
                   'since','etc','got','always',
                   'know','wa','thing','really',
                   'feel','find','even','go','would','well'
                  })
df['selftext']=df['selftext'].apply(lambda x: remove_stopwords(x))

In [11]:
anticipation_df=df[df['label']=='anticipation']
anticipation_df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,label
29,swimming place,1,0,50,0,0,0,0,0,0,anticipation
72,tell housey scene end moment curious see answer,4,0,120,0,59,0,0,0,0,anticipation
76,explore diversity electronic music r electroni...,1,144,446,111,229,181,165,0,348,anticipation
130,least year old kind moody vibe female vocal th...,3,0,188,54,60,62,0,0,175,anticipation
150,anybody planet song,1,0,56,0,0,0,0,0,0,anticipation
...,...,...,...,...,...,...,...,...,...,...,...
4805,check new tab occasionally quality house submi...,10,175,286,82,72,189,65,280,186,anticipation
4815,hey guy started producing deep house love hear...,11,0,152,0,0,140,0,0,143,anticipation
4820,something discus lil louis working documentary...,5,0,56,0,0,0,0,0,53,anticipation
4834,hope post break rule sub,3,0,77,0,0,58,0,0,68,anticipation
4839,hello everyone hope life treating current pand...,1,160,380,238,209,308,145,0,249,anticipation

In [12]:
#n-grams for anticipation
from nltk.util import ngrams
import itertools
import collections
def count_2gram(text):
    all_words = list(itertools.chain(*text.str.split()))
    es2grams = ngrams(all_words, 2)
    counts = collections.Counter(es2grams)
    count_df = pd.DataFrame(counts.most_common(100),
                            columns=['words', 'count'])
    dictionary2 = [' '.join(tup) for tup in count_df.words]
    count_df.words=dictionary2

    return count_df

count_df2=count_2gram(anticipation_df['selftext'])
count_df2.head(20)

                words  count
0      thanks advance     35
1         house music     31
2        original mix     21
3               lt lt     18
4          deep house     17
5   r electronicmusic     16
6         house track     16
7          tech house     13
8      recommend song     11
9           make sure     11
10       genre thread     11
11        disco house     11
12        track start     11
13         song start     11
14            hey guy     10
15            r house     10
16   electronic music      9
17           better u      9
18          need help      9
19          hope hear      9

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
#analyzer=â€˜char_wbâ€™
def tfidfvectorizer(df):
    vec=TfidfVectorizer(min_df=0.01,stop_words='english',ngram_range=(2,3))
    counts=vec.fit_transform(df['selftext'])
    counts=counts.toarray()
    count_df1=pd.DataFrame(counts,columns=vec.get_feature_names())
    return count_df1

count_df1=tfidfvectorizer(anticipation_df)
count_df1

,activity week,activity week people,antal hunee,best represent,best represent specific,better invite,better invite come,certain genre,certain genre upvoted,city drum,...,week people,week people submit,weekly genre,weekly genre thread,world tl,world tl dr,year ago,youtube channel,youtube com,youtube com watch
0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
1,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
2,0.094194,0.094194,0.0,0.086783,0.0,0.086783,0.097526,0.094194,0.094194,0.0,...,0.094194,0.094194,0.086783,0.086783,0.091376,0.091376,0.0,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
4,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
377,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
378,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
379,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
380,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0

In [14]:
from sklearn.decomposition import NMF

#n-components=number of topics
def nmf_topic(n_components,df):
    n=n_components
    model1=NMF(n_components=n,init="random",random_state=0)
    return model1.fit(df)

model1=nmf_topic(4,count_df1)
model1

NMF(init='random', n_components=4, random_state=0)

In [15]:
import numpy as np
def top_words(X, model, component, num_words):
    """
    Extract the top words from the specified component 
    for a topic model trained on data. 
    X: a term-document matrix, assumed to be a pd.DataFrame
    model: a sklearn model with a components_ attribute, e.g. NMF
    component: the desired component, specified as an integer. 
        Must be less than than the total number of components in model
    num_words: the number of words to return.
    """
    orders = np.argsort(model.components_, axis = 1)
    important_words = np.array(X.columns)[orders]
    return important_words[component][-num_words:]

In [16]:
#topic modeling for anticipation
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 10),
                   'Topic 1':top_words(count_df1, model1, 1, 10),
                   'Topic 2':top_words(count_df1, model1, 2, 10),
                     'Topic 3':top_words(count_df1, model1, 3, 10),
                   })
topic1

            Topic 0            Topic 1           Topic 2         Topic 3
0        house deep             hi guy       house track  track featured
1           hey guy  progressive house          live set    original mix
2      original mix          house mix  electronic music        house dj
3         sub genre         house deep      original mix        new york
4  recently started           hope guy          id track       need help
5        mix series            hey guy      house artist        id track
6          house dj      thank advance     looking house        hope guy
7            hi guy         tech house       track start      house song
8        tech house        house track       disco house     track start
9       house music         deep house    thanks advance      song start

In [17]:
#topic modeling for fear
fear_df=df[df['label']=='fear']

count_df1=tfidfvectorizer(fear_df)
model1=nmf_topic(3,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15)
                   })
topic1

                Topic 0           Topic 1            Topic 2
0           high energy      working hard            dj koze
1        thanks advance          year old            mix new
2         melodic house         house mix       robin schulz
3           nick warren        mix thanks         tech house
4        mix soundcloud       thanks help         house tech
5               new mix        thank help           year ago
6             long shot          set time      track similar
7             house set  claude vonstroke            hey guy
8             hello guy         new track        chill house
9   classic house track      original mix         acid house
10        classic house        house year  progressive house
11       track remember             xb xb      melodic house
12         original mix   looking forward         house song
13    progressive house        house song       house techno
14          house track       house music         deep house

In [18]:
#n-gram for fear
count_df2=count_2gram(fear_df['selftext'])
count_df2.head(20)

                words  count
0         house music     26
1         house track     17
2          deep house     15
3        original mix     11
4          house song     10
5   progressive house     10
6        house techno      8
7            track id      8
8               xb xb      7
9         anyone help      7
10          new track      7
11      classic house      7
12          long shot      6
13     hello everyone      6
14           year ago      6
15            r house      6
16     thanks advance      5
17   claude vonstroke      5
18         house tune      5
19         tech house      5

anticipation for:
topic0: Roth IRA and traditional IRA
topic1: tax and help with tax implication
topic2: funds and saving accounts
topic3: paying debts on cars and houses.

fear for:
topic0:credit card debt
topic1:car payment and student loan payment
topic3:roth ira

In [19]:
sadness_df=df[df['label']=='sadness']
#n-grams for sadness
count_df2=count_2gram(sadness_df['selftext'])
count_df2.head(20)

                      words  count
0                 lt iframe     14
1               house music     10
2              width height      7
3          encrypted medium      7
4                     gt lt      7
5                 iframe gt      7
6              original mix      5
7           picture picture      5
8              iframe width      4
9                height src      4
10          src frameborder      4
11        frameborder allow      4
12      allow accelerometer      4
13   accelerometer autoplay      4
14       autoplay encrypted      4
15         medium gyroscope      4
16        gyroscope picture      4
17  picture allowfullscreen      4
18       allowfullscreen gt      4
19                 year ago      4

In [20]:
#topic modeling for sadness
sadness_df=df[df['label']=='sadness']

count_df1=tfidfvectorizer(sadness_df)
model1=nmf_topic(4,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15),
                     'Topic 3':top_words(count_df1, model1, 3, 15)                   })
topic1

,Topic 0,Topic 1,Topic 2,Topic 3
0,encrypted medium gt,gyroscope picture picture,lost boy original,download zerosyx bandcamp
1,lt iframe src,picture allowfullscreen,boy original,melbourne australia pay
2,frameborder allowtransparency,picture allowfullscreen gt,boy original mix,download zerosyx
3,frameborder allowtransparency true,iframe width height,original mix dj,san francisco
4,height frameborder,frameborder allow accelerometer,dj vanwells soundcloud,tried searching
5,leave comment,frameborder allow,mix dj vanwells,listen time
6,listen time,accelerometer autoplay,mix dj,leave comment
7,dj mix,picture picture,dj vanwells,dj mix
8,san francisco,gt lt iframe,mix vocal,live set
9,song music,width height,original mix,house house
10,xb xb,encrypted medium,looking old,looking old
11,crystal castle,lt iframe gt,deep house,music pretty
12,vocal sample,iframe gt,tried searching,youtube house
13,best possible,gt lt,live set,youtube house music
14,year ago,lt iframe,tech house,house music

sadness for:
topic0: credit card service and debt
topic1:file tax and self-employed tax
topic2:missing payment for collection agencies
topic3:roth ira and aging

In [21]:
joy_df=df[df['label']=='joy']

#n-grams for joy
count_df2=count_2gram(joy_df['selftext'])
count_df2.head(20)

               words  count
0        house music    264
1         deep house    107
2        house track     82
3         tech house     80
4         hope enjoy     55
5              xb xb     48
6           mvrk shm     47
7        shm reunion     47
8       french house     39
9       original mix     37
10           hey guy     36
11         mashup xb     36
12           r house     34
13      house techno     33
14  help appreciated     30
15  wondering anyone     29
16        house song     28
17  electronic music     27
18        house tune     27
19       house house     26

In [22]:
#topic modeling for joy

count_df1=tfidfvectorizer(joy_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15),
                     'Topic 3':top_words(count_df1, model1, 3, 15),
                     'Topic 4':top_words(count_df1, model1, 4, 15),
                   })
topic1

,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4
0,classic house,hey guy,kerri chandler,original mix,help appreciated
1,new music,music love,sub genre,free download,free download
2,sub genre,house tech house,hi guy,classic house,house deep house
3,dance music,electronic music,house playlist,sub genre,house playlist
4,hey guy,house house,new house,love hear,music lover
5,xb xb,house tech,year ago,greatly appreciated,hi guy
6,music love,classic house,house song,help appreciated,house deep
7,help appreciated,house party,progressive house,new house,hey guy
8,thanks advance,house tune,long time,new music,house house
9,music lover,house song,hey guy,house set,house mix
10,house head,dance music,electronic music,hey guy,house dj
11,good house,house mix,free download,little bit,house tech house
12,new house,house deep,music love,hi guy,house tech
13,love house,house deep house,xb xb,favorite house,house techno
14,house music,deep house,hope enjoy,house track,tech house

joy for:
topic0:make money and pay debts
topic1:age and monthly payments
topic2:family and long-term invest
topic3:job matching and roth ira
topic4:investing and money saving

In [23]:
disgust_df=df[df['label']=='disgust']

#n-grams for joy
count_df2=count_2gram(disgust_df['selftext'])
count_df2.head(20)

                words  count
0         house music     28
1        original mix     22
2         house track     16
3                 z z     14
4          good house     12
5        looking song     12
6          deep house     12
7   looking something     11
8       looking track      9
9          tech house      9
10        anyone good      7
11        looking new      7
12     thanks looking      7
13      looking house      7
14          show love      7
15       looking good      6
16       french house      6
17            hey guy      6
18        guy looking      6
19        please help      6

In [24]:
#topic modeling for disguest

count_df1=tfidfvectorizer(disgust_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15)
                   })
topic1

                 Topic 0            Topic 1
0             type house          sub genre
1             house deep        looking new
2       house deep house          new house
3            style house      looking heavy
4    greatly appreciated         house song
5        hey guy looking        early house
6            guy looking      classic house
7                hey guy  progressive house
8          house looking         deep house
9   looking song similar         bass house
10        people looking         type house
11            hi looking        great track
12          song similar            hey guy
13            deep house           guy good
14          looking song        house music

disgust for:
topic0: mortgage company and mortgage rate
topic1: other topics(for disgust, mortgage rates and buying house is the most obvious topic, and the other topics doesn't make strong sense)

In [25]:
surprise_df=df[df['label']=='surprise']

#n-grams for surprise
count_df2=count_2gram(surprise_df['selftext'])
count_df2.head(20)

               words  count
0         house song      7
1   wondering anyone      4
2         make sense      3
3        couple week      3
4            lt song      3
5    absolute banger      3
6           week ago      3
7        couple year      3
8           year ago      3
9          show tell      3
10       beatus homo      2
11      homo brandon      2
12      brandon patr      2
13     track looking      2
14   looking banging      2
15         knee deep      2
16         long shot      2
17     popular track      2
18       point right      2
19   right direction      2

In [26]:
surprise_df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,label
27,mix mix named beatus homo brandon patr first t...,1,66,0,56,65,0,0,83,0,surprise
30,several bangin track automatik silk need cajua...,1,0,0,0,65,0,58,83,0,surprise
41,long shot anyone set list raf wood electric pi...,2,119,60,65,73,54,54,128,61,surprise
55,popular track woman humming song occasional check,2,0,0,0,0,0,0,50,0,surprise
66,popular track month sub posted together,1,0,0,0,0,0,0,50,0,surprise
...,...,...,...,...,...,...,...,...,...,...,...
4560,someone please upload amazing remix barbara tu...,1,0,50,0,71,56,0,84,77,surprise
4668,saw fedde play sensation toronto set song chor...,0,0,0,0,0,0,0,53,0,surprise
4707,moved bremen next month wondering anyone sugge...,1,0,0,0,65,113,0,135,0,surprise
4821,looking banging house electro house basically ...,0,0,0,56,65,0,0,83,75,surprise
4855,diz washington posted fb chicago heavy hitter ...,9,66,123,0,187,220,0,251,0,surprise

In [27]:
#topic modeling for surprise
count_df1=tfidfvectorizer(surprise_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15)})
topic1

C:\Users\ymf\anaconda3\lib\site-packages\sklearn\decomposition\_nmf.py:1076: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn("Maximum number of iterations %d reached. Increase it to"

              Topic 0
0   house song couple
1   future house song
2   drop future house
3         song couple
4    song couple year
5    sure drop future
6           sure drop
7    pretty sure drop
8         drop future
9        future house
10           year ago
11    couple year ago
12        pretty sure
13        couple year
14         house song

surprise for:
topic0: lower mortgage rate and buy house
(text labelled as surprise is not as many as those labelled other tags)

In [28]:
anger_df=df[df['label']=='anger']

#n-grams for anger
count_df2=count_2gram(anger_df['selftext'])
count_df2.head(20)

                    words  count
0            made content     24
1             house track     21
2       soundcloud listen     21
3              house song     19
4                 r house     18
5              tech house     18
6            anyone track     16
7            original mix     16
8               lt iframe     16
9            iframe width     16
10           width height     16
11       height scrolling     16
12  scrolling frameborder     16
13            house music     16
14      frameborder allow     15
15         allow autoplay     15
16           autoplay src     15
17             deep house     14
18        listen released     14
19          released swav     14

In [29]:
#topic modeling for anger

count_df1=tfidfvectorizer(anger_df)
model1=nmf_topic(3,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15)})
topic1

,Topic 0,Topic 1,Topic 2
0,scrolling frameborder allow,house music,content mix production
1,allow autoplay,lt iframe width,monthly stickied self
2,frameborder allow autoplay,house track,monthly stickied
3,frameborder allow,iframe width,mix production reoccur
4,autoplay src,iframe width height,mix production
5,allow autoplay src,lt iframe,dedicated user
6,width height,released swav,dedicated user content
7,lt iframe width,listen released swav,user content mix
8,lt iframe,swav soundcloud,production reoccur
9,iframe width height,released swav soundcloud,post removed directed
10,iframe width,listen released,house music
11,height scrolling frameborder,tech house,new house
12,height scrolling,new house,deep house
13,scrolling frameborder,deep house,tech house
14,width height scrolling,house song,house track

anger for:
topic0: insurance company and banks
topic1: loans and time(year ago)
topic2: brokerage account(special for this sentiment)

In [30]:
trust_df=df[df['label']=='trust']

#n-grams for trust
count_df2=count_2gram(trust_df['selftext'])
count_df2.head(20)

                    words  count
0             house music    198
1              deep house     76
2             house track     72
3                 hey guy     57
4              tech house     56
5                 r house     44
6          thanks advance     32
7                  hi guy     31
8              house song     31
9                 hip hop     28
10                dun dun     24
11            dance music     23
12             love house     23
13       anyone recommend     22
14       electronic music     22
15           house techno     21
16                  xb xb     21
17  anyone recommendation     20
18              love hear     19
19             old school     19

In [31]:
#topic modeling for trust

count_df1=tfidfvectorizer(trust_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15),
                    'Topic 3':top_words(count_df1, model1, 3, 15),
                    'Topic 4':top_words(count_df1, model1, 4, 15)})
topic1

,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4
0,song similar,reddiquette viewing,new track,electronic music,house tune
1,love hear,need help,need help,love hear,help appreciated
2,help appreciated,sub genre,greatly appreciated,right direction,greatly appreciated
3,new house,heard song,track id,year ago,electronic music
4,sub genre,house song,similar song,heard song,thanks advance
5,electronic music,new music,track heard,love house,sub genre
6,similar song,good house,help appreciated,old school,track heard
7,new music,hi guy,love hear,new music,kind music
8,love house,hip hop,hip hop,dj set,year ago
9,long time,electronic music,good house,house mix,house song
10,guy help,type house,house song,need help,hip hop
11,dance music,new house,classic house,guy help,house mix
12,house tune,love house,thanks advance,hi guy,house deep house
13,house song,thanks advance,hi guy,house techno,house deep
14,hey guy,house music,house track,tech house,deep house

trust for:
topic0:credit report and credit history
topic1:health insurance and social security
topic2:accounts and funds
topic3:car and student loans debt
topic4:good credit score